---
- name: Install package cloud gpg key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add apt repository
  apt_repository:
    repo: "{{ grafana_apt_repo }}"
    state: present

- name: Install Grafana package
  apt:
    name: "{{ grafana_pkg }}"
    state: present
  notify:
    - Restart grafana
