---

- include: yum.yaml
  when: ansible_pkg_mgr == "yum"
  tags:
    - grafana_pkg

- include: apt.yaml
  when: ansible_pkg_mgr == "apt"
  tags:
    - grafana_pkg

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart grafana
  tags:
    - grafana_config

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/sbin/grafana-server | grep cap_net_bind_service
  register: grafana_bind_cap
  failed_when: False
  changed_when: False
  when: grafana_allow_low_port
  tags:
    - grafana_config

- name: Set capability on the binary file to be able to bind to TCP port <1024
  shell: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
  when: grafana_allow_low_port and grafana_bind_cap.rc > 0
  notify:
    - Restart grafana
  tags:
    - grafana_config

- name: Make sure grafana service is enabled and running
  service:
    name: grafana-server
    enabled: yes
    state: running
